INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (1,'Victoria Point Veterinary Hospital','7/15 Bunker Rd, Victoria Point QLD',4165);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (2,'Melbourne Bird Veterinary Clinic','1 George St, Scoresby VIC',3179);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (3,'Monash Veterinary Clinic','1662 Dandenong Rd, Oakleigh East VIC',1662);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (4,'Carlton Vet Clinic','603 Rathdowne St, Carlton North VIC',3054);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (5,'Main Ridge Veterinary Clinic','334 Main Creek Rd, Main Ridge VIC',3928);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (6,'Richmond Veterinary Clinic','259 Church St, Richmond VIC',3121);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (7,'Templestowe Veterinary Clinic and Cattery','288 Manningham Rd, Templestowe Lower VIC',3107);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (8,'Boronia Veterinary Clinic and Hospital','181 Boronia Rd, Boronia VIC',3155);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (9,'Berwick Veterinary Hospital','58 Clyde Rd, Berwick VIC',3806);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (10,'Johnston Street Veterinary Clinic & Hospital - Fitzroy','206 Johnston St, Fitzroy VIC',3065);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (11,'Maribyrnong Veterinary Clinic','95A Rosamond Rd, Maidstone VIC',3012);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (12,'Port Phillip Animal Hospital','364 Richardson St, Middle Park VIC',3206);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (13,'Wyndham Veterinary Clinic','133 Market Rd, Werribee VIC',3030);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (14,'Hampton Veterinary Clinic','6 Thomas St, Melbourne VIC',3188);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (15,'Healthy Pets Veterinary Clinic','9 Elizabeth St, Castlemaine VIC',3450);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (16,'Elsternwick Veterinary Clinic','627 Glen Huntly Rd, Caulfield VIC',3162);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (17,'Rosanna Veterinary Clinic','47 Beetham Parade, Rosanna VIC',3084);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (18,'Bird & Exotic Animal Clinic','19 Ponting St, Williamstown VIC',3016);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (19,'Yarra Ranges Animal Hospital','484 Maroondah Hwy, Lilydale VIC',3140);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (20,'Newtown Veterinary Clinic','121 W Fyans St, Newtown VIC',3220);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (21,'Glenhuntly Road Veterinary Clinic','1111 Glen Huntly Road, Glen Huntly, Glen Huntly VIC',1111);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (22,'Brunswick Central Vet Clinic','210 Lygon St, Brunswick East VIC',3055);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (23,'Greensborough Veterinary Hospital','505 Greensborough Rd, Greensborough VIC',3088);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (24,'Northcote Plaza Veterinary Clinic','43A Dennis St, Northcote VIC',3070);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (25,'Malvern Vet Hospital','547 Dandenong Rd, Armadale VIC',3143);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (26,'Cheltenham Veterinary Clinic','1172 Nepean Hwy, Cheltenham VIC',1172);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (27,'Altona Veterinary Clinic','97 Pier St, Altona VIC',3018);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (28,'Albert Park Vet','17 Victoria Ave, Albert Park VIC',3206);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (29,'Mansfield Veterinary Clinic','265 Mt Buller Rd, Mansfield VIC',3722);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (30,'Alexandra Veterinary Clinic','49 Bayley St, Alexandra VIC',3714);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (31,'Dandenong Veterinary Hospital','118 Princes Hwy, Dandenong VIC',3175);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (32,'Ferntree Gully Veterinary Hospital','1288 Burwood Hwy, Upper Ferntree Gully VIC',1288);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (33,'Gisborne Veterinary Clinic','12 Robertson St, Gisborne VIC',3437);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (34,'Chirnside Park Veterinary Clinic','103 Switchback Rd, Chirnside Park VIC',3116);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (35,'Lower Plenty Veterinary Clinic','164 Main Rd, Lower Plenty VIC',3093);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (36,'Warrandyte Veterinary Clinic','91 Melbourne Hill Rd, Warrandyte VIC',3113);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (37,'Reservoir Veterinary Clinic','226 Spring St, Reservoir VIC',3073);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (38,'West Brunswick Veterinary Clinic','169 Dawson St, Brunswick West VIC',3055);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (39,'Belgrave South Veterinary Clinic','136 Belgrave-Hallam Rd, Belgrave South VIC',3160);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (40,'Eureka Veterinary Clinic (Ballarat)','121 Creswick Rd, Ballarat Central VIC',3350);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (41,'Epsom Road Veterinary Clinic','156 Epsom Rd, Ascot Vale VIC',3032);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (42,'Hawthorn East Vet','1 Victoria Rd, Hawthorn East VIC',3123);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (43,'Pets Haven Veterinary Clinic','302/304 Canterbury Rd, Bayswater North VIC',3153);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (44,'South Eastern Animal Hospital','1357 Centre Rd, Clayton VIC',1357);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (45,'Equine Centre','250 Princes Hwy, Werribee VIC',3030);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (46,'Canterbury Veterinary Clinic','721 Canterbury Rd, Surrey Hills VIC',3127);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (47,'Hobsons Bay Veterinary Clinic','318 Melbourne Rd, Newport VIC',3015);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (48,'Craigieburn Animal Hospital','9 Craigieburn Rd, Craigieburn VIC',3064);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (49,'Lort Smith Animal Hospital','24 Villiers St, North Melbourne VIC',3051);
INSERT INTO pranav(id,Clinic_Name,Address,PostCode) VALUES (50,'Port Melbourne Veterinary Clinic','109 Bay St, Port Melbourne VIC',3207);
