//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoenixRnR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pranav
    {
        public int id { get; set; }
        public string Clinic_Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> PostCode { get; set; }
    }
}
